# Generated by Django 5.2.6 on 2025-10-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0002_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
    ]
