# Generated by Django 5.2.6 on 2025-10-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0005_devotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text="Short title for the testimony (e.g., 'Healed from sickness')", max_length=150)),
                ('message', models.TextField(help_text='Full testimony message')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonies/')),
                ('date_shared', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_shared'],
            },
        ),
    ]
