# Generated by Django 5.2.6 on 2025-10-10 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0006_testimony'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(help_text='Details of the prayer request')),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_answered', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
    ]
