# Generated by Django 5.2.6 on 2025-10-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0007_prayerrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayerrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='prayerrequest',
            old_name='date_submitted',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='is_answered',
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
