# Generated by Django 5.2.6 on 2025-10-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0010_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Youth', 'Youth Ministry'), ('Women', 'Women Ministry'), ('Men', 'Men Ministry'), ('Children', 'Children Ministry'), ('Choir', 'Choir & Worship Team'), ('Project', 'Church Project')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='ministries/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
