# Generated by Django 5.2.6 on 2025-10-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0012_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default=1, upload_to='gallery/'),
            preserve_default=False,
        ),
    ]
