# Generated by Django 5.2.6 on 2025-10-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0013_gallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
    ]
