# Generated by Django 5.2.6 on 2025-10-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0014_remove_gallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Church Live Stream', max_length=255)),
                ('url', models.URLField(help_text='Enter the embed link (e.g., YouTube embed URL)')),
                ('is_active', models.BooleanField(default=False, help_text='Check if this stream is active')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
