# Generated by Django 5.2.6 on 2025-10-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0016_alter_prayerrequest_options_prayerrequest_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayerrequest',
            name='user',
        ),
    ]
