# Generated by Django 5.2.6 on 2025-10-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0017_remove_prayerrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotion',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='devotions/pdfs/'),
        ),
    ]
